import * as T from 'three';
import {Board,type Cell} from '../match3';
import {Player} from '../player';
import {installMobilityControls} from '../mobilityControls';
import {makeWorld,height,point,R} from './world';
import {CanvasView} from './fallback';
import {SITES,LEVELS,fresh,restore,level,reachable,cost,enter,discover,act,tick,type SiteId} from './state';
import './style.css';

const $=<E extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as E;
document.body.innerHTML=`
<canvas id="world" aria-label="Hulda's living world. Drag to look; use WASD or the movement stick to walk."></canvas><div id="shade"></div>
<header><button id="brand" class="brand">ROOTWAKE<span>AN EXPERIMENT IN LIVING DISTANCE</span></button><button id="journal">The becoming <span>↗</span></button></header>
<section id="heading"><div class="eyebrow" id="mode-label">HULDA · IN HER OWN BODY</div><h1 id="title">Beneath the<br>living world.</h1><p id="subtitle">The earth remembers every footstep.<br>The roots remember everyone.</p></section>
<div id="energy"><div><span>STORED LIFE</span><strong id="energy-number">0 <small>/ 240</small></strong></div><div class="meter"><i id="energy-fill"></i></div><p id="rank"></p></div>
<div id="labels"></div><select id="thread-picker" aria-label="Living threads within reach" hidden></select><div id="notice" role="status" aria-live="polite"></div>
<section id="site-card" hidden><div class="eyebrow" id="site-kind"></div><h2 id="site-name"></h2><p id="site-copy"></p><div id="site-actions"></div><button id="close-card" class="text-button">Release this thread</button></section>
<section id="board-panel" hidden aria-label="Cultivation match-three"><div class="row"><div><span class="eyebrow">CULTIVATION</span><h2>Gather the light.</h2></div><button id="close-board" aria-label="Close cultivation">×</button></div><p id="board-copy">Swap two neighboring shapes. Every match becomes stored life.</p><div id="board" role="group" aria-label="Select two adjacent gems to swap"></div><div class="row"><span id="board-result">No energy is spent on failed swaps.</span><button id="hint">Hint</button></div></section>
<footer><div id="objective"><span class="eyebrow">THE NEXT THREAD</span><p id="objective-copy"></p></div><div id="actions"><button id="cultivate">Cultivate</button><button id="commune" class="primary">Touch the roots · 36</button><button id="return" hidden>Return to the surface</button><button id="view">First person</button></div></footer>
<div id="tools"><button id="walk" aria-label="Movement stick"></button></div><div id="timer" hidden></div>
<dialog id="journal-dialog"><button id="close-journal" class="close" aria-label="Close progression">×</button><span class="eyebrow">SEVEN GIFTS · ONE LIVING WORLD</span><h2>The becoming</h2><p>Hulda is the first connection. Her council helps the world build connections of its own.</p><div id="progression"></div><h3>A council, wherever it is needed</h3><p>Herbalist · Alchemist · Sage · Mason · Smith · Artificer · Steward</p><p>In this slice, the Mason answers one invitation and establishes a road. The other council members, trade, passenger transport, and the daughter's conflict are future systems.</p><h3>Beyond the horizon</h3><p>A complete small spherical world is generated from a fixed seed, with authored settlements and encounter sites. The study below lets you inspect its interior without unlocking any abilities. Drag to turn your gaze toward the opposite hemisphere.</p><button id="study">Planet interior study</button><p class="muted">Controls: drag to look, WASD or the thumbstick to walk. In communion, drag to drift under the roots; select a glowing place. Match-three is turn-based. Communion lasts 75 active seconds; a dryad lasts 90. Menus and hidden tabs pause both.</p><p id="save-status"></p><button id="export">Export journey</button><button id="reset">Start a fresh journey</button></dialog>
<dialog id="welcome"><span class="eyebrow">HULDA'S ROOTS · PLAYABLE SKETCH</span><h2>A world you can feel.</h2><p>Stand beside the Listening Tree. Gather at least <b>54 energy</b> through match-three: 36 to enter the roots, 18 to release a trapped spring.</p><p>Then look up from beneath the soil. Follow the light to a knot in the roots. Each problem you solve teaches Hulda a new way to be present.</p><p class="muted">About 10–15 minutes. Saves on this browser. Sound is not required.</p><button id="begin" class="primary">Stand with Hulda</button></dialog>`;
const SAVE='rootwake.rootvision.v1';let s=fresh(),saveOK=true;
try{const raw=localStorage.getItem(SAVE);if(raw)s=restore(JSON.parse(raw));}catch{saveOK=false;}
let board=new Board(6,6,s.seed);try{for(const[a,b]of s.moves)if(!board.swap(cell(a),cell(b)).valid)throw Error('Invalid replay');}catch{s=fresh();board=new Board(6,6,s.seed);}
let mode:'surface'|'roots'|'study'='surface',selected:SiteId|null=null,chosen:number|null=null,communionLeft=75,boardOpen=false;
let noticeUntil=0,last=0,rootX=0,rootZ=0,studyYaw=0,studyPitch=.3,transition=1;
const canvas=$<HTMLCanvasElement>('world');
let renderer:T.WebGLRenderer|CanvasView;try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch{renderer=new CanvasView(canvas);}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const scene=new T.Scene();scene.background=new T.Color('#b8c9b7');scene.fog=new T.FogExp2('#b8c9b7',.006);
scene.add(new T.HemisphereLight('#e4e8c9','#456358',2.5));const sun=new T.DirectionalLight('#ffe1a9',3);sun.position.set(-40,90,20);scene.add(sun);
const camera=new T.PerspectiveCamera(55,innerWidth/innerHeight,.1,650),world=makeWorld(scene),player=new Player(canvas,scene,camera);installMobilityControls(player);
player.position.y=0;scene.add(player.avatar);player.view='third';player.thirdBackScale=2;player.thirdZoom=1.1;player.standHeightAt=(x,z)=>height(x,z);player.onTap=onTap;
const dryad=new T.Group();scene.add(dryad);const body=new T.Mesh(new T.ConeGeometry(.5,1.4,7),new T.MeshStandardMaterial({color:'#a7dcaa',emissive:'#375c49',transparent:true,opacity:.6}));body.position.y=.7;dryad.add(body);const head=new T.Mesh(new T.IcosahedronGeometry(.27,1),new T.MeshStandardMaterial({color:'#d1e9bb',emissive:'#487d55'}));head.position.y=1.6;dryad.add(head);
const mason=new T.Group();scene.add(mason);const coat=new T.Mesh(new T.BoxGeometry(.9,1.1,.6),new T.MeshStandardMaterial({color:'#8b9dba'}));coat.position.y=.7;mason.add(coat);const helm=new T.Mesh(new T.IcosahedronGeometry(.4,1),new T.MeshStandardMaterial({color:'#ccad76'}));helm.position.y=1.4;mason.add(helm);mason.position.copy(point(51,-62));
const ray=new T.Raycaster();const physicalPosition=new T.Vector3();
function spawn(id:SiteId,offset=5){const site=SITES[id];player.teleport(site.x,site.z+offset,0,height(site.x,site.z+offset));player.pitch=0;}
spawn(s.body);physicalPosition.copy(player.position);
function cell(n:number):Cell{return{row:Math.floor(n/6),col:n%6};}
function persist(){try{localStorage.setItem(SAVE,JSON.stringify(s));saveOK=true;}catch{saveOK=false;}}
function notify(text:string){$('notice').textContent=text;noticeUntil=performance.now()+6500;}
function modal(){return !!document.querySelector('dialog[open]');}
function treeNear():SiteId|null {for(const[id,v]of Object.entries(SITES))if(id!=='daughter'&&Math.hypot(player.position.x-v.x,player.position.z-v.z)<7)return id as SiteId;return null;}
function controls(){player.enabled=mode==='surface'&&!boardOpen&&!modal();if(!player.enabled)player.cancelInput();$('tools').hidden=!player.enabled;}
function closeBoard(){boardOpen=false;$('board-panel').hidden=true;chosen=null;controls();refresh();}
function cultivate(){if(s.dryad){notify('A borrowed body can tend the grove, but only your true body can store life.');return;}if(!treeNear()){notify('Walk closer to a living tree to cultivate.');return;}boardOpen=true;$('board-panel').hidden=false;drawBoard();controls();refresh();}
function rootView(study=false){if(s.dryad){notify('Return from your borrowed body first.');return;}if(!study){const near=treeNear();if(!near){notify('Walk within reach of a living tree first.');return;}const e=enter(s);if(e){notify(e);return;}s.body=near;}closeBoard();physicalPosition.copy(player.position);mode=study?'study':'roots';communionLeft=75;rootX=SITES[s.body].x;rootZ=SITES[s.body].z-5;selected=null;transition=0;controls();persist();refresh();notify(study?'WORLD STUDY · A preview of the whole planet’s interior. No progression is changed.':'You are beneath the earth. The forest is above you. Follow a glowing root.');}
function surface(){mode='surface';selected=null;transition=0;controls();refresh();}
function select(id:SiteId){if(!(id in SITES)||mode!=='roots'||!reachable(s,id))return;discover(s,id);selected=id;rootX=SITES[id].x;rootZ=SITES[id].z;persist();refresh();}
function action(action:'mend'|'speak'|'dryad'|'cleanse'|'cross'|'council'){
 if(!selected)return;const id=selected;
 if(action==='cleanse'&&Math.hypot(player.position.x-SITES.grove.x,player.position.z-SITES.grove.z)>7){notify('Walk closer to the bitter roots at the grove.');return;}
 const e=act(s,id,action);if(e){notify(e);return;}
 const messages={mend:'Water moves again. A new thought enters the roots: you can speak.',speak:'The villagers agree to spare the young trees. Their trust teaches you to borrow a body.',dryad:'Your true body remains behind. You have 90 seconds in this borrowed dryad.',cleanse:'The grove breathes. You remember how to let the roots carry your true body.',cross:'Your body becomes root, then leaf, then breath. You have crossed.',council:'The Mason answers. The first road belongs to the people who will maintain it.'};
 if(action==='dryad'||action==='cross'){spawn(id,action==='dryad'?10:5);mode='surface';if(action==='cross')physicalPosition.copy(player.position);selected=action==='dryad'&&id==='grove'?'grove':null;transition=0;}
 if(action==='mend'||action==='speak'||action==='cleanse')communionLeft=75;
 persist();controls();refresh();notify(messages[action]);
}
function returnDryad(){s.dryad=null;s.dryadLeft=0;player.teleport(physicalPosition.x,physicalPosition.z,0,height(physicalPosition.x,physicalPosition.z));mode='surface';selected=null;persist();controls();refresh();notify('The borrowed body falls into leaves. You wake where you began.');}
function btn(text:string,actionName:string,disabled=false){return `<button data-action="${actionName}" ${disabled?'disabled':''}>${text}</button>`;}
function refresh(){
 const l=level(s),below=mode!=='surface';document.body.dataset.mode=mode;
 $('energy-number').innerHTML=`${Math.floor(s.energy)} <small>/ 240</small>`;$('energy-fill').style.width=`${s.energy/240*100}%`;$('rank').textContent=`${String(l+1).padStart(2,'0')} / ${LEVELS[l].name} · ${LEVELS[l].range} m reach`;
 $('mode-label').textContent=mode==='study'?'PLANET INTERIOR · FUTURE REACH STUDY':below?'HULDA · THROUGH THE ROOTS':s.dryad?'HULDA · A BORROWED BODY':'HULDA · IN HER OWN BODY';
 $('title').innerHTML=mode==='study'?'A planet,<br>from within.':below?'The world<br>from beneath.':s.dryad?'A body<br>made of leaves.':'Beneath the<br>living world.';
 $('subtitle').textContent=below?'Drag to move your gaze. Select a living thread.':s.dryad?'Your true body is safe. Walk to the bitter roots.':'Drag to look. Walk with the stick or WASD.';
 $('objective-copy').textContent=s.council?'A road now carries what once required a miracle. Explore, or review the becoming.':l===0?'Gather 54 life. Commune with a tree. Release the Knotted Spring.':l===1?'Find the blank clearing. Speak to its people through their tree.':l===2?'Borrow a dryad at the Moonseed Grove. Walk to its roots and tend them.':'Return to your body. Cross through a known tree, or invite the Mason to Stoneward Pass.';
 $('cultivate').hidden=below||!!s.dryad;$('commune').hidden=below||!!s.dryad;$('commune').textContent=`Touch the roots · ${cost(s,'listen')}`;$('commune').toggleAttribute('disabled',s.energy<cost(s,'listen'));
 $('return').hidden=!below&&!s.dryad;$('return').textContent=s.dryad?'Return to your true body':'Return to the surface';$('view').hidden=below;$('view').textContent=player.view==='third'?'First person':'Third person';
 $('site-card').hidden=!selected;if(selected){const id=selected,site=SITES[id];$('site-kind').textContent=site.kind;$('site-name').textContent=site.name;$('site-copy').textContent=s.solved.includes(id)?({spring:'Clear water follows the roots. Your reach has grown.',village:'“We heard you. We will leave the saplings, if you can help us find another way.” The village is listening.',grove:'White leaves unfold. This grove can now receive your true body.',pass:'The Mason has taught the villagers to lay a road. Everyday transport can now outlast your visit.',home:'Your true body rests beneath this tree.',daughter:''}[id]):site.description;
 let buttons='';if(mode==='roots'){
  if(id==='spring'&&!s.solved.includes(id))buttons+=btn('Release the knotted roots · 18','mend',s.energy<18);
  if(id==='village'&&!s.solved.includes(id))buttons+=btn('Promise a living future · 12','speak',l<1||s.energy<12);
  if(l>=2)buttons+=btn('Emerge as a dryad · 36','dryad',s.energy<36);
  if(l>=3&&id!==s.body)buttons+=btn(`Carry your true body · ${cost(s,'cross',id)}`,'cross',s.energy<cost(s,'cross',id));
  if(id==='pass'&&l>=3&&!s.council)buttons+=btn(`Invite the Mason · ${cost(s,'council',id)}`,'council',s.energy<cost(s,'council',id));
 }else if(id==='grove'&&s.dryad==='grove'&&!s.solved.includes(id))buttons+=btn('Gently untangle the bitter roots','cleanse');
 $('site-actions').innerHTML=buttons;for(const b of $('site-actions').querySelectorAll<HTMLButtonElement>('button'))b.onclick=()=>action(b.dataset.action as Parameters<typeof action>[0]);}
 $('timer').hidden=!below&&!s.dryad;updateLabels();
 $('thread-picker').hidden=mode!=='roots';$('thread-picker').innerHTML='<option value="">Follow a living thread…</option>'+(Object.keys(SITES) as SiteId[]).filter(id=>reachable(s,id)).map(id=>`<option value="${id}" ${selected===id?'selected':''}>${s.discovered.includes(id)?SITES[id].name:SITES[id].kind}</option>`).join('');
}
function drawBoard(hint:number[]=[]){const focused=document.activeElement instanceof HTMLElement?document.activeElement.dataset.gem:undefined;const colors=['#91c991','#e5b66d','#81bfd3','#c39ada','#e79591'],shapes=['◆','●','▲','✦','⬟'];$('board').innerHTML=board.grid.flat().map((g,i)=>`<button data-gem="${i}" aria-label="${['Leaf','Sun','Water','Memory','Bloom'][g.type]}, row ${Math.floor(i/6)+1}, column ${i%6+1}" aria-pressed="${chosen===i}" class="gem ${chosen===i?'selected':''} ${hint.includes(i)?'hint':''}" style="--gem:${colors[g.type]}">${shapes[g.type]}</button>`).join('');
 for(const b of $('board').querySelectorAll<HTMLButtonElement>('button')){const i=Number(b.dataset.gem);b.onclick=()=>choose(i);b.onkeydown=e=>{const delta:Record<string,number>={ArrowLeft:-1,ArrowRight:1,ArrowUp:-6,ArrowDown:6};if(e.key in delta){e.preventDefault();const next=Math.max(0,Math.min(35,i+delta[e.key]));$('board').querySelector<HTMLButtonElement>(`[data-gem="${next}"]`)?.focus();}};let down:{x:number;y:number}|null=null;b.onpointerdown=e=>{down={x:e.clientX,y:e.clientY};};b.onpointerup=e=>{if(!down)return;const dx=e.clientX-down.x,dy=e.clientY-down.y;if(Math.hypot(dx,dy)>20){const j=i+(Math.abs(dx)>Math.abs(dy)?Math.sign(dx):Math.sign(dy)*6);if(j>=0&&j<36&&Board.adjacent(cell(i),cell(j))){chosen=i;choose(j);}}down=null;};}
 if(focused)$('board').querySelector<HTMLButtonElement>(`[data-gem="${focused}"]`)?.focus();
}
function choose(i:number){if(chosen===null){chosen=i;drawBoard();return;}if(chosen===i){chosen=null;drawBoard();return;}if(!Board.adjacent(cell(chosen),cell(i))){chosen=i;drawBoard();return;}const a=chosen,r=board.swap(cell(a),cell(i));chosen=null;if(r.valid){const n=r.steps.reduce((sum,step)=>sum+step.cleared.length,0),gain=Math.min(36,n*3);s.energy=Math.min(240,s.energy+gain);s.moves.push([a,i]);$('board-result').textContent=`+${gain} life · ${n} gems answered`;persist();refresh();}else $('board-result').textContent='Those roots do not connect. Try another pair.';drawBoard();}
function hint(){for(let a=0;a<36;a++)for(const b of[a+1,a+6])if(b<36&&Board.adjacent(cell(a),cell(b))){const copy=new Board(6,6,s.seed);for(const[x,y]of s.moves)copy.swap(cell(x),cell(y));if(copy.swap(cell(a),cell(b)).valid){chosen=null;drawBoard([a,b]);return;}}}
function journal(){controls();$('progression').innerHTML=LEVELS.map((v,i)=>`<div class="stage ${i<=level(s)?'earned':''}"><b>${String(i+1).padStart(2,'0')}</b><div><strong>${v.name}</strong><p>${v.ability} ${v.range} m reach; communion costs ${v.cost}.</p></div><span>${i<=level(s)?'●':'○'}</span></div>`).join('')+`<div class="stage"><b>05</b><div><strong>Carry & trade</strong><p>Future: cargo, passengers, and exceptional transport. Roads carry routine trade.</p></div><span>○</span></div><div class="stage"><b>06</b><div><strong>The far side</strong><p>Future: your daughter, the silenced roots, and the choice of how to overcome.</p></div><span>○</span></div>`;$('save-status').textContent=saveOK?'Journey saved in this browser.':'Browser storage is unavailable. Export your journey before leaving.';$<HTMLDialogElement>('journal-dialog').showModal();controls();}
function onTap(x:number,y:number){if(modal()||boardOpen)return;ray.setFromCamera(new T.Vector2(x/innerWidth*2-1,-y/innerHeight*2+1),camera);if(mode==='roots'){const hits=ray.intersectObjects(Object.values(world.beacons).filter(b=>b.visible));if(hits[0])select(hits[0].object.userData.site);}else if(mode==='surface'){const hit=ray.intersectObjects(Object.values(world.treesAt),true)[0];if(hit&&hit.distance<15){if(s.dryad==='grove'){selected='grove';refresh();}else if(treeNear())cultivate();}}}
const labelEls={} as Record<SiteId,HTMLButtonElement>;for(const id of Object.keys(SITES) as SiteId[]){if(id==='daughter')continue;const b=document.createElement('button');b.className='map-label';b.onclick=()=>select(id);$('labels').append(b);labelEls[id]=b;}
function updateLabels(){for(const [key,b]of Object.entries(labelEls)){const id=key as SiteId,site=SITES[id];b.hidden=mode!=='roots'||!reachable(s,id);b.textContent=(s.solved.includes(id)?'✧ ':'')+(s.discovered.includes(id)?site.name:id==='village'?'A gap in the roots':id==='spring'?'A thirsty knot':id==='grove'?'A pale memory':'A distant thread');}}
player.onOrbit=(dx,dy)=>{if(modal()||boardOpen)return;if(mode==='roots'){rootX=Math.max(SITES[s.body].x-45,Math.min(SITES[s.body].x+45,rootX-dx*24));rootZ=Math.max(SITES[s.body].z-65,Math.min(SITES[s.body].z+25,rootZ+dy*24));}else if(mode==='study'){studyYaw-=dx;studyPitch=Math.max(-1.4,Math.min(1.4,studyPitch+dy));}};
// HUD buttons share the same domain commands as pointer interactions.
$('cultivate').onclick=cultivate;$('commune').onclick=()=>rootView();$('return').onclick=()=>s.dryad?returnDryad():surface();$('close-board').onclick=closeBoard;$('hint').onclick=hint;$('close-card').onclick=()=>{selected=null;refresh();};$('view').onclick=()=>{player.view=player.view==='third'?'first':'third';refresh();};$('journal').onclick=journal;$('brand').onclick=journal;$<HTMLSelectElement>('thread-picker').onchange=e=>select((e.target as HTMLSelectElement).value as SiteId);
$('close-journal').onclick=()=>{$<HTMLDialogElement>('journal-dialog').close();controls();};$('study').onclick=()=>{$<HTMLDialogElement>('journal-dialog').close();rootView(true);};$('reset').onclick=()=>{if(!confirm('Start again? This replaces the saved root journey on this browser.'))return;s=fresh();board=new Board(6,6,s.seed);mode='surface';selected=null;spawn('home');physicalPosition.copy(player.position);closeBoard();$<HTMLDialogElement>('journal-dialog').close();persist();controls();refresh();};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hulda-root-journey.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('begin').onclick=()=>{$<HTMLDialogElement>('welcome').close();controls();};for(const d of document.querySelectorAll('dialog'))d.addEventListener('close',controls);
document.addEventListener('visibilitychange',()=>{last=performance.now();player.cancelInput();persist();});window.addEventListener('pagehide',persist);
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
function frame(now:number){requestAnimationFrame(frame);const dt=Math.min(.05,(now-(last||now))/1000);last=now;
 if(!document.hidden&&!modal()){if(s.dryad&&tick(s,dt))returnDryad();if(mode==='roots'){communionLeft-=dt;if(communionLeft<=0){surface();notify('The listening fades. Your body waits safely above.');}}}
 if(mode==='surface')player.update(now,[],p=>Math.hypot(p.x,p.z)<125);
 const below=mode!=='surface';world.update(s,below,now,mode==='study');mason.visible=s.council;dryad.visible=!!s.dryad&&player.view==='third';dryad.position.copy(player.feet());
 const targetPosition=new T.Vector3(),targetLook=new T.Vector3();
 if(mode==='surface'){player.applyCamera(camera);}else if(mode==='roots'){const focus=point(rootX,rootZ);targetPosition.copy(focus).add(new T.Vector3(0,-34,28));targetLook.copy(focus).add(new T.Vector3(0,1,-9));camera.position.lerp(targetPosition,transition<1?.065:.12);camera.up.set(0,1,0);camera.lookAt(targetLook);}else{camera.position.lerp(new T.Vector3(0,-R,0),.06);targetLook.set(Math.sin(studyYaw)*Math.cos(studyPitch),Math.sin(studyPitch),-Math.cos(studyYaw)*Math.cos(studyPitch)).multiplyScalar(R).add(new T.Vector3(0,-R,0));camera.lookAt(targetLook);}
 player.avatar.visible=mode==='surface'&&player.view==='third'&&!s.dryad;
 transition=Math.min(1,transition+dt);const background=below?'#081c21':'#b8c9b7';(scene.background as T.Color).lerp(new T.Color(background),.08);(scene.fog as T.FogExp2).color.copy(scene.background as T.Color);(scene.fog as T.FogExp2).density=mode==='study'?.001:below?.009:.006;
 $('timer').textContent=mode==='study'?'STUDY ONLY · drag to look around the interior':s.dryad?`BORROWED BODY · ${Math.ceil(s.dryadLeft)} s`:`COMMUNION · ${Math.ceil(communionLeft)} s`;
 if(now>noticeUntil)$('notice').textContent='';
 camera.updateMatrixWorld();for(const[key,b]of Object.entries(labelEls)){if(b.hidden)continue;const site=SITES[key as SiteId],p=point(site.x,site.z,-4).project(camera);const visible=p.z<1&&p.z>-1&&Math.abs(p.x)<.94&&Math.abs(p.y)<.9;b.style.visibility=visible?'visible':'hidden';b.style.left=`${(p.x+1)*.5*innerWidth}px`;b.style.top=`${(-p.y+1)*.5*innerHeight}px`;}
 renderer.render(scene,camera);
}
refresh();controls();if(s.moves.length===0&&!s.solved.length){$<HTMLDialogElement>('welcome').showModal();controls();}requestAnimationFrame(frame);
