import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright'));}
const root=resolve('dist'),out=resolve('artifacts/village');await mkdir(out,{recursive:true});
const BASE=process.env.STUDY_BASE??'/Rootwake/village/';
const server=createServer(async(req,res)=>{try{let path=new URL(req.url,'http://localhost').pathname;if(path.startsWith(BASE))path='/'+path.slice(BASE.length);if(path==='/')path='/village.html';if(path==='/favicon.ico'){res.writeHead(204).end();return;}const file=resolve(root,'.'+path);if(!file.startsWith(root+'/'))throw Error('Bad path');res.setHeader('Content-Type',{'.html':'text/html','.js':'application/javascript','.css':'text/css'}[extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(4187,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const report=[];
const stick=(page,id)=>({down:async(dx,dy)=>{await page.locator('#walk').dispatchEvent('pointerdown',{pointerId:id,clientX:315,clientY:710,pointerType:'touch',bubbles:true});await page.locator('#walk').dispatchEvent('pointermove',{pointerId:id,clientX:315+dx,clientY:710+dy,pointerType:'touch',bubbles:true});},up:async()=>{await page.locator('#walk').dispatchEvent('pointerup',{pointerId:id,clientX:315,clientY:710,pointerType:'touch',bubbles:true});await page.waitForTimeout(150);}});
const v=(page,expr)=>page.evaluate(expr);
const waitMode=(page,m,timeout=20000)=>page.waitForFunction(m=>window.__village.mode===m,m,{timeout});
// The four events go in one go: the tap's thresholds are wall-clock, and a slow frame between them (the karst's scene under the software renderer) would otherwise undo the tap.
async function singleTapStick(page){await page.evaluate(()=>{const w=document.getElementById('walk');for(const type of ['pointerdown','pointerup'])w.dispatchEvent(new PointerEvent(type,{pointerId:23,clientX:315,clientY:710,pointerType:'touch',bubbles:true}));});await page.waitForTimeout(450);}
async function doubleTapStick(page){await page.evaluate(()=>{const w=document.getElementById('walk');for(const id of [21,22]){for(const type of ['pointerdown','pointerup'])w.dispatchEvent(new PointerEvent(type,{pointerId:id,clientX:315,clientY:710,pointerType:'touch',bubbles:true}));}});await page.waitForTimeout(150);}
const touch=(id,x,y)=>({pointerId:id,clientX:x,clientY:y,pointerType:'touch',isPrimary:true,bubbles:true});
async function press(page,x,y,holdMs=120){const canvas=page.locator('canvas').first();await canvas.dispatchEvent('pointerdown',touch(7,x,y));await page.waitForTimeout(holdMs);await canvas.dispatchEvent('pointerup',touch(7,x,y));}
try{
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});page.on('dialog',d=>d.accept());const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
 await page.goto('http://127.0.0.1:4187'+BASE);await page.click('#begin');await page.waitForFunction(()=>window.__village&&window.__village.character.status!=='loading',null,{timeout:120000});
 const character=await v(page,()=>window.__village.character);assert.equal(character.status,'ready',character.error);assert.deepEqual(character.roles,{idle:'idle',walk:'walking',run:'running'});assert.equal(character.hobbitWeights.filter(Boolean).length,8,'the eight hobbits have the clips too');
 assert.equal(await v(page,()=>window.__village.player.view),'third','Third person');assert.equal(await page.locator('#hint, #story, #actions button:visible').count(),0,'no hints');
 // Dawn: eight hobbits, all indoors; the clock reads day one, six o'clock or a little after.
 assert.equal(await v(page,()=>window.__village.hobbits.length),8);assert.equal(await v(page,()=>window.__village.houses.length),6);
 const start=await v(page,()=>({tick:window.__village.tick,inside:window.__village.count('inside'),clock:window.__village.clock}));assert.ok(start.tick<200,'starts at dawn on a fresh page');assert.equal(start.clock.day,1);
 await page.waitForTimeout(700);await page.screenshot({path:out+'/01-dawn.png'});
 // Hulda walks the meadow toward the green.
 const z0=await v(page,()=>window.__village.player.feet().z);const s=stick(page,1);await s.down(0,-38);await page.waitForFunction(z=>window.__village.player.feet().z>z+1.5,z0,{timeout:15000});await s.up();
 // Time passes only while watched: a real second is about 1.2 ticks.
 const t0=await v(page,()=>window.__village.tick);await page.waitForTimeout(3000);const t1=await v(page,()=>window.__village.tick);assert.ok(t1-t0>=2&&t1-t0<=6,`ticks in three seconds: ${t1-t0}`);
 // W1, her hands: standing in the thicket's ring fills her stack with a meal's berries in a few seconds; a loaded stack refuses the grass (a wobble); the baskets' ring takes it. Then the pickers, supplied, go to the stone and pray, and prayer pools.
 await v(page,()=>{const k=window.__village;k.speed=0;const st=k.stations.find(s=>s.id==='gather-thicket');k.standAt(st.x,st.z,0);});await page.waitForTimeout(4500);
 const stack=await v(page,()=>window.__village.stack);assert.ok(stack&&stack.kind==='berries'&&stack.n>=6,`a stack of berries from standing in the ring (${JSON.stringify(stack)})`);assert.ok(await v(page,()=>window.__village.land.berries<35),'off the bushes');
 await doubleTapStick(page);await page.waitForTimeout(400);assert.equal(await v(page,()=>window.__village.mode),'ground','a loaded stack refuses the grass');
 // With the baskets full she is told so and collects only the overfill; the heap beside the rack takes it.
 await v(page,()=>{const k=window.__village;k.setStore('berries',8);const st=k.stations.find(s=>s.id==='gather-thicket');k.standAt(st.x,st.z,0);});await page.waitForTimeout(2500);
 assert.ok(await page.locator('#tip').isVisible()&&/full/.test(await page.locator('#tip').textContent()),'the tip says the baskets are full');assert.ok((await v(page,()=>window.__village.stack.n))<=8,'her stack is bounded by the room');
 await v(page,()=>{const k=window.__village;k.setStore('berries',0);const st=k.stations.find(s=>s.id==='deliver-berries');k.standAt(st.x,st.z,0);});await page.waitForTimeout(2500);
 const handed=await v(page,()=>({stack:window.__village.stack,berries:window.__village.stores.berries}));assert.ok(!handed.stack,`handed over, all of it (${JSON.stringify(handed)})`);assert.equal(handed.berries,8,`the baskets hold it (${handed.berries})`);
 await page.screenshot({path:out+'/02e-stack.png'});
 const prayed=await v(page,()=>{const k=window.__village;k.setStore('milk',8);k.setStore('grain',12);k.advance(200-k.tick);for(let i=0;i<20;i++){k.advance(10);if(k.praying().length>0)break;}return {praying:k.praying(),prayer:k.prayer};});assert.ok(prayed.praying.length>0,`supplied, someone prays (${JSON.stringify(prayed)})`);
 // Before the stone with prayer enough, the miracle is offered; asked, a spirit for the thicket appears and takes up the job.
 await v(page,()=>{const k=window.__village;k.prayer=60;const st=k.stations.find(s=>s.id==='shrine');k.standAt(st.x,st.z,0);});await page.waitForSelector('#miracles:not([hidden])',{timeout:8000});assert.ok(await page.locator('#miracles').isVisible(),'the miracles offered before the stone');
 await page.click('#miracles [data-keeps="thicket"]');await page.waitForTimeout(300);const sp=await v(page,()=>({n:window.__village.spirits.length,prayer:window.__village.prayer,figures:window.__village.figures.length}));assert.equal(sp.n,1,'a spirit summoned');assert.ok(sp.prayer<60,'prayer spent');
 const worked=await v(page,()=>{const k=window.__village;let carried=false;for(let i=0;i<60&&!carried;i++){k.advance(10);carried=!!k.spirits[0].carry;}return carried;});assert.ok(worked,'the spirit gathers');await page.screenshot({path:out+'/02f-spirit.png'});
 await v(page,()=>{window.__village.reset();window.__village.speed=1;});await page.waitForTimeout(300);
 // The Dark Young: at half past eight one shambles in from the wood for the fullest store; the fight buttons strike it, burst thorns and bind it; the vigor and sap bars are there.
 await v(page,()=>{const k=window.__village;k.speed=0;k.setTick(890);});await page.waitForTimeout(300);assert.equal(await v(page,()=>window.__village.raiders().length),1,'one Dark Young the first night');
 await v(page,()=>{window.__village.speed=30;});await page.waitForFunction(()=>window.__village.raiders()[0]&&window.__village.raiders()[0].state==='eating',null,{timeout:30000});await v(page,()=>{window.__village.speed=1;});
 const foe=await v(page,()=>{const k=window.__village,r=k.raiders()[0];k.standAt(r.x-1.3,r.z,Math.atan2(-(r.x-(r.x-1.3)),-(r.z-r.z)));k.player.pitch=.15;return r;});await page.waitForTimeout(500);await page.screenshot({path:out+'/06-dark-young.png'});
 assert.equal(await page.locator('#fight button').count(),3,'three fight buttons');assert.ok(await page.locator('#vigor b').isVisible()&&await page.locator('#sap b').isVisible(),'vigor and sap bars');
 await page.locator('#strike').dispatchEvent('pointerdown',{pointerId:31,clientX:340,clientY:600,pointerType:'touch',bubbles:true});await page.waitForTimeout(150);assert.ok((await v(page,()=>window.__village.raiders()[0].hp))<30,'the strike lands');
 await page.locator('#thorn').dispatchEvent('pointerdown',{pointerId:32,clientX:340,clientY:540,pointerType:'touch',bubbles:true});await page.waitForTimeout(150);const afterThorn=await v(page,()=>({hp:window.__village.raiders()[0].hp,sap:window.__village.hero.sap}));assert.ok(afterThorn.hp<30-5&&afterThorn.sap<100,`the burst lands and spends sap (${JSON.stringify(afterThorn)})`);
 await page.locator('#root').dispatchEvent('pointerdown',{pointerId:33,clientX:340,clientY:480,pointerType:'touch',bubbles:true});await page.waitForTimeout(150);assert.ok((await v(page,()=>window.__village.raiders()[0].rooted))>0,'the bind holds it');
 assert.ok(await page.locator('#labels .name.foe:not(.lair)').first().isVisible(),'its name and hp over its head');
 // D2: beaten, it does not die. Rooted and with her beside it, it is held (the tip counts down the melt); when she steps away the bind runs down and it runs for its mother, flat and fast.
 for(let i=0;i<12;i++){await page.waitForFunction(()=>window.__village.cooldowns.strike===0,null,{timeout:5000});await page.locator('#strike').dispatchEvent('pointerdown',{pointerId:34+i,clientX:340,clientY:600,pointerType:'touch',bubbles:true});await page.waitForTimeout(80);if(await v(page,()=>window.__village.raiders()[0].state==='retreating'))break;}
 const beaten=await v(page,()=>{const r=window.__village.raiders()[0];return {state:r.state,hp:r.hp,rooted:r.rooted,slain:window.__village.slain};});assert.equal(beaten.state,'retreating','beaten, it retreats');assert.equal(beaten.slain,0,'not slain');assert.ok(beaten.rooted>0,'still in the roots');
 await page.waitForTimeout(1200);const heldNow=await v(page,()=>{const r=window.__village.raiders()[0];return {rooted:r.rooted,held:r.held,tip:document.getElementById('tip').textContent};});assert.ok(heldNow.rooted>0&&heldNow.held>0.5,`held while she stands by it (${JSON.stringify(heldNow)})`);assert.ok(/held in the roots/.test(heldNow.tip),'the hold told');await page.screenshot({path:out+'/06b-held.png'});
 const fled=await v(page,()=>{const k=window.__village,r=k.raiders()[0];k.standAt(r.x-12,r.z,Math.atan2(-(r.x-(r.x-12)),0));return {x:r.x,z:r.z};});await page.waitForFunction(()=>{const r=window.__village.raiders()[0];return !r||r.rooted===0;},null,{timeout:10000});await page.waitForTimeout(700);
 const away=await v(page,()=>{const r=window.__village.raiders()[0];return r?{state:r.state,x:r.x,z:r.z}:null;});assert.ok(!away||(away.state==='retreating'&&Math.hypot(away.x-fled.x,away.z-fled.z)>2),`off it runs (${JSON.stringify(away)})`);await page.screenshot({path:out+'/06c-fleeing.png'});
 // The night's end: fed, the Dark Young devour a place of the land and leave their leavings; the place is spoiled for a day, then clean again.
 const spoiled=await v(page,()=>{const k=window.__village;k.reset();k.setTick(880);k.speed=30;return new Promise(res=>{let n=0;const tick=()=>{const l=k.land,any=Object.entries(l.spoiled).find(([,t])=>t>0);if(any||++n>2400)res({site:any?any[0]:null,dark:k.stores.dark,tick:k.tick,events:k.events.map(e=>e.text)});else requestAnimationFrame(tick);};tick();});});
 assert.ok(spoiled.site,`a place spoiled in the night (${JSON.stringify(spoiled)})`);assert.ok(spoiled.dark>0,'their leavings left on the heap');assert.ok(spoiled.events.some(e=>e.endsWith('is spoiled')),'told');
 await v(page,()=>{window.__village.speed=0;});await page.evaluate(s=>{const k=window.__village,st=k.sites[s];k.standAt(st.x-4,st.z,Math.atan2(-(st.x-(st.x-4)),0));},spoiled.site);await page.waitForTimeout(900);await page.screenshot({path:out+'/06d-spoiled.png'});
 const clean=await page.evaluate(s=>{const k=window.__village;k.setTick(k.tick+k.dayTicks+5);return k.land.spoiled[s]>k.tick?1:0;},spoiled.site);assert.equal(clean,0,'clean again a day on');
 await v(page,()=>{window.__village.reset();window.__village.speed=1;});await page.waitForTimeout(300);
 // The pinch (M1): two fingers closing pull the camera overhead, continuously; at the end a further pinch opens the map of what she has seen, with the village and the karst marked; the button closes it. Exploring reveals cells.
 async function pinch(from,to,steps=8){const c=page.locator('canvas').first();const mid={x:195,y:400};const at=(d)=>[{x:mid.x-d/2,y:mid.y},{x:mid.x+d/2,y:mid.y}];let [a,b]=at(from);await c.dispatchEvent('pointerdown',{pointerId:41,clientX:a.x,clientY:a.y,pointerType:'touch',isPrimary:true,bubbles:true});await c.dispatchEvent('pointerdown',{pointerId:42,clientX:b.x,clientY:b.y,pointerType:'touch',isPrimary:false,bubbles:true});for(let i=1;i<=steps;i++){const d=from+(to-from)*i/steps;[a,b]=at(d);await c.dispatchEvent('pointermove',{pointerId:41,clientX:a.x,clientY:a.y,pointerType:'touch',bubbles:true});await c.dispatchEvent('pointermove',{pointerId:42,clientX:b.x,clientY:b.y,pointerType:'touch',bubbles:true});await page.waitForTimeout(30);}await c.dispatchEvent('pointerup',{pointerId:41,clientX:a.x,clientY:a.y,pointerType:'touch',bubbles:true});await c.dispatchEvent('pointerup',{pointerId:42,clientX:b.x,clientY:b.y,pointerType:'touch',bubbles:true});await page.waitForTimeout(100);}
 const yaw0=await v(page,()=>window.__village.player.yaw);await pinch(300,120);const z1=await v(page,()=>window.__village.zoom);assert.ok(z1>6,`a pinch pulls the camera out (${z1.toFixed(1)} m)`);assert.ok(Math.abs((await v(page,()=>window.__village.player.yaw))-yaw0)<0.05,'without turning the look');
 await page.waitForTimeout(300);await page.screenshot({path:out+'/07-overhead.png'});
 await pinch(300,40);assert.ok((await v(page,()=>window.__village.zoom))>=39.9,'to the top');assert.ok(!(await v(page,()=>window.__village.mapOpen)),'the map waits for one pinch more');
 await pinch(300,120);assert.ok(await v(page,()=>window.__village.mapOpen),'pinching on past the top opens the map');assert.ok(await page.locator('#mapwrap').isVisible());await page.screenshot({path:out+'/07b-map.png'});
 const known=await v(page,()=>window.__village.known());assert.ok(known.includes('village')&&known.includes('karst')&&!known.includes('lair'),`the village and the karst marked, the lair unknown (${known})`);assert.ok((await v(page,()=>window.__village.explored))>10,'the cells she has seen');
 await page.click('#mapclose');assert.ok(!(await v(page,()=>window.__village.mapOpen)),'closed');await pinch(60,300);assert.ok((await v(page,()=>window.__village.zoom))<10,'a spread brings the camera back');
 // The land beyond the meadow (M1a.2): out past the wood the chunks are loaded round her, with trees she can stand by and climb; the ground rises and falls; back at the village nothing has changed.
 await v(page,()=>{window.__village.standAt(0,190,0);});await page.waitForTimeout(600);const beyond=await v(page,()=>{const k=window.__village;return {chunks:k.chunks(),near:k.treesNear(0,190,60).length,y:k.relief(0,190),y2:k.relief(120,260),feet:k.player.feet().y};});
 assert.ok(beyond.chunks.loaded>=20&&beyond.chunks.trees>0,`chunks loaded round her with trees (${JSON.stringify(beyond.chunks)})`);assert.ok(beyond.near>0,"trees of the land near her");assert.ok(Math.abs(beyond.feet-beyond.y)<0.2,'she stands on the land\'s height');
 const ct=await v(page,()=>{const k=window.__village,f=k.player.feet(),ts=k.treesNear(f.x,f.z,80).filter(t=>t.id>=100000).sort((a,b)=>Math.hypot(a.x-f.x,a.z-f.z)-Math.hypot(b.x-f.x,b.z-f.z));const t=ts[0];const a=Math.atan2(f.z-t.z,f.x-t.x);k.standAt(t.x+Math.cos(a)*1.2,t.z+Math.sin(a)*1.2,Math.atan2(-(t.x-(t.x+Math.cos(a)*1.2)),-(t.z-(t.z+Math.sin(a)*1.2))));return t;});await page.waitForTimeout(300);
 await s.down(0,-38);await waitMode(page,'trunk',15000);await s.up();assert.equal((await v(page,()=>window.__village.trunk)).tree,ct.id,'a chunk tree takes her in');await page.screenshot({path:out+'/08-land.png'});await doubleTapStick(page);await page.waitForFunction(()=>window.__village.mode==='ground',null,{timeout:10000});
 await v(page,()=>{window.__village.standAt(0,-16,Math.PI);});await page.waitForTimeout(300);
 // The karst in the land (M1a.3): walk onto its forest floor and it is her ground; a stick double tap near one of its plants takes her into the roots as in the free-flow study; out again, and back to the meadow.
 await v(page,()=>{const k=window.__village,o=k.karst.origin;k.standAt(o.x+50,o.z+40,Math.atan2(-(o.x-(o.x+50)),-(o.z-(o.z+40))));});await page.waitForTimeout(700);
 const onKarst=await v(page,()=>{const k=window.__village,f=k.player.feet();return {inside:k.karst.inside(f.x,f.z),zone:k.karst.zone,y:f.y,chunks:k.chunks().loaded};});assert.ok(onKarst.inside&&onKarst.zone==='floor',`on the karst's floor (${JSON.stringify(onKarst)})`);await page.screenshot({path:out+'/09-karst.png'});
 await v(page,()=>{const k=window.__village,o=k.karst.origin,n=Object.values(k.karst.nodes).filter(n=>n.zone==='floor').sort((a,b)=>Math.hypot(a.at.x-50,a.at.z-40)-Math.hypot(b.at.x-50,b.at.z-40))[0];k.standAt(o.x+n.at.x+1.5,o.z+n.at.z,0);});await page.waitForTimeout(300);
 // The karst's scene is heavy for the software renderer: its sink and rise take many slow frames.
 await doubleTapStick(page);await page.waitForFunction(()=>window.__village.mode==='grass',null,{timeout:30000});assert.ok((await v(page,()=>window.__village.karst.at)).length>0,'at a root mouth of the karst');await page.screenshot({path:out+'/09b-karst-roots.png'});
 await doubleTapStick(page);await page.waitForFunction(()=>window.__village.mode==='ground',null,{timeout:30000});assert.equal(await v(page,()=>window.__village.karst.mode),'ground','out again');
 // The portal (R1, Noah's C): a tree at the foot of the karst offers the places its roots reach; picked, the roots carry her up by themselves and she rises out there.
 await v(page,()=>{const k=window.__village,o=k.karst.origin,n=k.karst.nodes.floorOak;k.standAt(o.x+n.at.x+1.6,o.z+n.at.z,0);});await page.waitForTimeout(300);
 assert.ok(await v(page,()=>window.__village.portal.open('floorOak')),'the foot oak is a portal');assert.ok(await page.locator('#portal').isVisible(),'its places are offered');
 const offered=await v(page,()=>window.__village.portal.places());assert.ok(offered.includes('cavernFern')&&offered.includes('pine')&&offered.includes('southShrub'),`the cavern, the summit and the south ledge (${offered})`);
 await v(page,()=>window.__village.portal.pick('southShrub'));await page.waitForFunction(()=>window.__village.mode==='karst'&&window.__village.karst.travelling,null,{timeout:5000});
 await page.waitForFunction(()=>window.__village.karst.mode==='ride',null,{timeout:30000});await page.screenshot({path:out+'/09c-portal-ride.png'});
 await page.waitForFunction(()=>window.__village.mode==='ground'&&window.__village.karst.zone==='south',null,{timeout:180000});await page.screenshot({path:out+'/09d-portal-arrived.png'});
 await v(page,()=>{window.__village.standAt(0,-16,Math.PI);});await page.waitForTimeout(300);assert.ok(!(await v(page,()=>{const f=window.__village.player.feet();return window.__village.karst.inside(f.x,f.z);})),'back in the meadow, the karst has no say');
 // The dark forest and the lair (M1b): in the forest her vigor drains; near the lair the mother of goats wakes with her hp over her, a strike lands on her, and a slain Dark Young counts toward a level whose choice is offered.
 // The forest drains at the clock's pace, so the clock runs.
 const lairAt=await v(page,()=>window.__village.lair().at);await page.evaluate(({x,z})=>{const k=window.__village;k.speed=1;k.standAt(x+50,z,Math.atan2(-(x-(x+50)),-(z-z)));},lairAt);await page.waitForTimeout(600);
 const inForest=await v(page,()=>{const k=window.__village,f=k.player.feet();return {depth:k.forestDepth(f.x,f.z),v0:k.hero.vigor};});assert.ok(inForest.depth>0,'in the dark forest');await page.waitForTimeout(1500);assert.ok((await v(page,()=>window.__village.hero.vigor))<inForest.v0,'it drains her');await page.screenshot({path:out+'/10-forest.png'});
 await page.evaluate(({x,z})=>{const k=window.__village;k.standAt(x+4,z,Math.atan2(-(x-(x+4)),-(z-z)));},lairAt);await page.waitForFunction(()=>window.__village.lair().woke,null,{timeout:8000});assert.ok(await page.locator('#labels .name.lair').isVisible(),'the mother of goats named over her');await page.screenshot({path:out+'/10b-lair.png'});
 const lhp=await v(page,()=>window.__village.lair().hp);await page.locator('#strike').dispatchEvent('pointerdown',{pointerId:51,clientX:340,clientY:600,pointerType:'touch',bubbles:true});await page.waitForTimeout(200);assert.ok((await v(page,()=>window.__village.lair().hp))<lhp,'a strike lands on the lair');
 await v(page,()=>{const k=window.__village;k.xp=1;k.standAt(0,-16,Math.PI);k.vigor=100;});const lv=await v(page,()=>{const k=window.__village;return {level:k.hero.level,text:document.getElementById('level').textContent};});assert.ok(/level 1/.test(lv.text),`the level shown (${lv.text})`);
 await v(page,()=>{window.__village.setTick(890);window.__village.speed=30;});await page.waitForFunction(()=>window.__village.raiders()[0]&&window.__village.raiders()[0].state==='eating',null,{timeout:30000});await v(page,()=>{window.__village.speed=0;const k=window.__village,r=k.raiders()[0];k.standAt(r.x-1.3,r.z,Math.atan2(-(r.x-(r.x-1.3)),0));});
 // Strike as the cooldown clears (it runs down a frame at a time, so a fixed beat misses on the runner's slow frames) until it is dead.
 for(let i=0;i<20;i++){await page.waitForFunction(()=>window.__village.cooldowns.strike===0,null,{timeout:5000});await page.locator('#strike').dispatchEvent('pointerdown',{pointerId:60+i,clientX:340,clientY:600,pointerType:'touch',bubbles:true});await page.waitForTimeout(80);if(await v(page,()=>{const r=window.__village.raiders()[0];return !r||r.state==='retreating';}))break;}
 // D2: beaten it would run; rooted and held (she stands by it) for HOLD_MELT_S it melts, and the melt counts toward the level.
 await page.waitForFunction(()=>window.__village.cooldowns.root===0,null,{timeout:5000});await page.locator('#root').dispatchEvent('pointerdown',{pointerId:59,clientX:340,clientY:480,pointerType:'touch',bubbles:true});await page.waitForTimeout(100);assert.ok((await v(page,()=>window.__village.raiders()[0].rooted))>0,'bound where it stands');
 await v(page,()=>{window.__village.speed=30;});await page.waitForFunction(()=>window.__village.slain>=1,null,{timeout:30000});await v(page,()=>{window.__village.speed=0;});assert.ok((await v(page,()=>window.__village.raiders()[0]?.state))!=='retreating','melted');
 await page.waitForSelector('#perks:not([hidden])',{timeout:8000});assert.equal(await v(page,()=>window.__village.hero.level),2,'the kill made level two');await page.screenshot({path:out+'/10c-level.png'});await page.click('#perks [data-perk="strike"]');await page.waitForTimeout(200);assert.equal(await v(page,()=>window.__village.hero.perks.strike),1,'the choice taken');await page.waitForFunction(()=>document.getElementById('perks').hidden,null,{timeout:5000});// the panel goes on the next frame, which is slow near the lair on the software renderer
 await v(page,()=>{window.__village.reset();window.__village.speed=1;});await page.waitForTimeout(300);
 // The compass: a strip at the top that turns with her; the karst's mark a little west of north; a ghost finger never haunts the pinch count.
 assert.ok(await page.locator('#compass').isVisible(),'the compass strip');const cmp=await v(page,()=>{const k=window.__village;k.player.yaw=0;return k.compass();});assert.ok(Math.abs(cmp.heading)<1,`facing north at yaw 0 (${cmp.heading.toFixed(0)})`);const kmark=cmp.marks.find(m=>m.id==='karst');assert.ok(kmark&&kmark.bearing>330&&kmark.distance>300,`the karst marked to the north (${JSON.stringify(kmark)})`);
 await page.evaluate(()=>{const c=document.querySelector('canvas');c.dispatchEvent(new PointerEvent('pointerdown',{pointerId:77,clientX:100,clientY:300,pointerType:'touch',bubbles:true}));c.dispatchEvent(new PointerEvent('pointerleave',{pointerId:77,clientX:100,clientY:300,pointerType:'touch',bubbles:true}));});assert.equal(await v(page,()=>window.__village.pinchPointers()),0,'a finger that leaves is forgotten');
 await v(page,()=>{window.__village.player.yaw=Math.PI;});
 // The clock's dev control: tap the clock, jump an hour, to noon, to the next dawn, run at thirty times; the village follows.
 await page.click('#clock');assert.ok(await page.locator('#timectl').isVisible(),'the time panel opens on the clock');await v(page,()=>{window.__village.speed=0;});// the clock held still, so the jumps are exact
 const tc0=await v(page,()=>window.__village.tick);await page.click('#timectl [data-jump="60"]');assert.equal(await v(page,()=>window.__village.tick),tc0+60,'an hour on');
 await page.click('#timectl [data-to="noon"]');assert.equal(await v(page,()=>window.__village.tick%1440),330,'to noon');assert.ok((await v(page,()=>window.__village.count('green')))>=0);
 await page.click('#timectl [data-to="dawn"]');assert.equal(await v(page,()=>window.__village.tick),1440,'to the next dawn (a day on)');
 await page.click('#timectl [data-jump="-60"]');assert.equal(await v(page,()=>window.__village.tick),1380,'an hour back, replayed');
 await page.click('#timectl [data-speed="30"]');await page.waitForTimeout(1200);const fast=await v(page,()=>window.__village.tick);assert.ok(fast>=1380+20,`thirty times: ${fast-1380} ticks in a second`);await page.click('#timectl [data-speed="1"]');
 // Dev (Noah): the village started over from the panel, its people, stores and spirits back to the first dawn; the panel closes.
 await v(page,()=>{window.__village.prayer=60;window.__village.summon('thicket');});await page.click('#timectl [data-reset]');await page.waitForTimeout(200);const fresh=await v(page,()=>({tick:window.__village.tick,spirits:window.__village.spirits.length,population:window.__village.population}));assert.deepEqual(fresh,{tick:0,spirits:0,population:8},`started over (${JSON.stringify(fresh)})`);assert.ok(await page.locator('#timectl').isHidden(),'the panel closes');await page.click('#clock');await page.click('#clock');
 await v(page,()=>window.__village.setTick(0));
 // Morning: they are out at their places, walking with the walk clip, names over their heads when near.
 await v(page,()=>{window.__village.advance(200-window.__village.tick);window.__village.player.teleport(0,-5,Math.PI);window.__village.player.pitch=.05;});await page.waitForTimeout(1500);
 assert.equal(await v(page,()=>window.__village.count('inside')),0,'all out by morning');assert.equal(await v(page,()=>window.__village.figures.filter(f=>f.group.visible).length),8,'eight figures shown');
 await page.screenshot({path:out+'/02-morning.png'});
 const walked=await v(page,()=>new Promise(res=>{let best=0,n=0;const tick=()=>{const c=window.__village;for(let i=0;i<8;i++){const w=c.character.hobbitWeights[i];if(w&&c.shown[i].speed>.3)best=Math.max(best,w.walk+w.run);}if(++n<240&&best<.5)requestAnimationFrame(tick);else res(best);};tick();}));assert.ok(walked>.5,`a walking hobbit plays the walk clip (${walked.toFixed(2)})`);
 // Beside one of them, facing it (they walk on while the frames above are waited out, so where they are is not assumed): its name is in view.
 await v(page,()=>{const k=window.__village,h=k.shown[0];k.player.teleport(h.x+2,h.z+2,Math.atan2(-(h.x-(h.x+2)),-(h.z-(h.z+2))));});
 const named=await page.waitForFunction(()=>window.__village.shown.some(s=>s.label),null,{timeout:5000}).then(()=>true,()=>false);
 assert.ok(named,`a name in view: ${JSON.stringify(await v(page,()=>{const k=window.__village,c=k.camera.position;return {mode:k.mode,zoom:k.zoom,map:k.mapOpen,feet:k.player.feet(),cam:[c.x,c.y,c.z],h:k.shown[0],faint:k.hero.faint};}))}`);
 // They face the way they walk, and think out loud: what they are doing, or where they are going.
 const facing=await v(page,()=>new Promise(res=>{let forward=0,samples=0,n=0;const tick=()=>{for(const f of window.__village.facing())if(f.moving){samples++;if(f.dot>0.5)forward++;}if(++n<240)requestAnimationFrame(tick);else res({forward,samples});};tick();}));assert.ok(facing.samples>20&&facing.forward/facing.samples>0.8,`walkers face forward (${facing.forward} of ${facing.samples} walking frames)`);
 const thoughts=await v(page,()=>window.__village.thoughts());assert.ok(thoughts.some(t=>t==='gathering berries'||t.startsWith('carrying berries'))&&thoughts.some(t=>t==='milking the goats'||t.startsWith('carrying milk')),JSON.stringify(thoughts));assert.ok(thoughts.every(t=>t.length>0),'everyone out has a thought');
 // V1, the land and the stores: by mid-morning someone carries an armful, shown in the hand; the stores hold what was handed over, under their caps; a hunger bar sits under every name.
 // The stores fill in the first hours (gathering is bounded by their caps), so the armfuls are looked for through the morning: the day is wound back to seven and stepped until someone carries.
 const armful=await v(page,()=>{const k=window.__village;k.advance(0);const w=JSON.parse(localStorage.getItem('rootwake-village-v1'));return new Promise(res=>{k.reset();let n=0;const step=()=>{k.advance(4);const c=k.carrying(),j=c.findIndex(x=>x);if(j>=0||k.tick>=300){requestAnimationFrame(()=>{const a=k.armfuls();res(j<0?null:{who:k.hobbits[j].id,carry:c[j],shown:a[j],tick:k.tick});});}else if(++n<200)step();else res(null);};step();});});
 assert.ok(armful,'someone carries an armful in the morning');assert.equal(armful.shown,armful.carry.kind,`the ${armful.carry.kind} shows in ${armful.who}'s hand at ${armful.tick}`);
 await v(page,()=>{window.__village.advance(220-window.__village.tick);window.__village.player.teleport(0,-5,Math.PI);});await page.waitForTimeout(600);
 const stores=await v(page,()=>({stores:window.__village.stores,caps:Object.fromEntries(Object.entries(window.__village.storeSpots).map(([k,s])=>[k,s.cap]))}));for(const k of Object.keys(stores.stores))assert.ok(stores.stores[k]>=0&&stores.stores[k]<=stores.caps[k],`${k} within its cap`);
 assert.equal(await page.locator('#labels .name:not(.foe) .hunger b').count(),8,'a hunger bar under every name');
 await v(page,()=>{const k=window.__village,s=k.storeSpots.berries;k.player.teleport(s.x*0.35,s.z*0.35,Math.atan2(-(s.x-s.x*0.35),-(s.z-s.z*0.35)));k.player.pitch=.12;});await page.waitForTimeout(600);await page.screenshot({path:out+'/02d-stores.png'});
 const land=await v(page,()=>window.__village.land);assert.ok(land.berries<=35&&land.crops.length===5,'the land is in the model');
 // Her ways: double tap the ground and she is a bulge under the grass, faster than running; run along a tree root and it takes her, faster still and held to it; double tap out.
 await v(page,()=>{window.__village.standAt(-14,-2,Math.PI/2);});await page.waitForTimeout(300);await doubleTapStick(page);await waitMode(page,'sink',5000);await waitMode(page,'grass',5000);
 assert.ok((await v(page,()=>window.__village.under))>0.3||true,'under');
 const g0=await v(page,()=>({g:window.__village.grass,t:window.__village.simSeconds}));await s.down(0,-38);await page.waitForTimeout(1000);const g1=await v(page,()=>({g:window.__village.grass,t:window.__village.simSeconds}));await s.up();
 if(g1.g){const d=Math.hypot(g1.g.x-g0.g.x,g1.g.z-g0.g.z),speed=d/Math.max(1e-3,g1.t-g0.t);assert.ok(speed>3.2,`the grass carries her at ${speed.toFixed(1)} m/s (faster than running)`);}
 await page.screenshot({path:out+'/02b-grass.png'});
 // A copse root runs between the first two copse trees that are joined (every tree joins its nearest three): under the grass a step off its line, one stick tap takes her onto it (R1: no root takes her by itself). Running along it first proves that.
 const lane=await v(page,()=>{const k=window.__village,c=k.trees.slice(0,6),a=c[0];const b=c.slice(1).sort((p,q)=>Math.hypot(p.x-a.x,p.z-a.z)-Math.hypot(q.x-a.x,q.z-a.z))[0];const dx=b.x-a.x,dz=b.z-a.z,l=Math.hypot(dx,dz);return {x:a.x+dx/l*1.4-dz/l*0.3,z:a.z+dz/l*1.4+dx/l*0.3,yaw:Math.atan2(-dx/l,-dz/l)};});
 await page.evaluate(({x,z,yaw})=>{window.__village.sinkAt(x,z);window.__village.player.yaw=yaw;},lane);await waitMode(page,'grass',5000);
 await s.down(0,-38);await page.waitForTimeout(500);assert.equal(await v(page,()=>window.__village.mode),'grass','running along a root no longer takes her');await s.up();
 await singleTapStick(page);await waitMode(page,'root',5000);
 // And one tap is off it again, into the grass; then back on for the ride.
 await singleTapStick(page);await waitMode(page,'grass',5000);await singleTapStick(page);await waitMode(page,'root',5000);
 // Along the root: the camera turns to its heading, so pushing forward follows it; she is carried faster than she walks, or reaches its end or a junction.
 await page.waitForTimeout(400);const r0=await v(page,()=>({root:window.__village.root,t:window.__village.simSeconds}));await s.down(0,-38);await page.waitForTimeout(1200);const r1=await v(page,()=>({root:window.__village.root,mode:window.__village.mode,t:window.__village.simSeconds}));await s.up();
 const carried=r1.mode!=='root'||r1.root.root!==r0.root.root||Math.abs(r1.root.s-r0.root.s)/(r1.t-r0.t)>2.5||Math.abs(r1.root.s-r0.root.s)>2||r1.root.s>r1.root.length-0.1||r1.root.s<0.1;assert.ok(carried,`the root carries her (${JSON.stringify({r0,r1})})`);
 await page.screenshot({path:out+'/02c-root.png'});await doubleTapStick(page);await page.waitForFunction(()=>window.__village.mode==='ground',null,{timeout:10000});
 // Out is always possible: from a trunk, and from a root's end at a tree of the wood beyond the meadow (where she could not stand before), the stick double tap brings her back to her feet on the ground.
 const far=await v(page,()=>{const k=window.__village,t=k.trees.filter(t=>Math.hypot(t.x,t.z)>46&&!k.inWater(t.x,t.z)).sort((a,b)=>Math.hypot(a.x,a.z)-Math.hypot(b.x,b.z))[0];return {x:t.x,z:t.z};});
 await page.evaluate(({x,z})=>{const k=window.__village;const a=Math.atan2(z,x);k.standAt(x-Math.cos(a)*1.0,z-Math.sin(a)*1.0,Math.atan2(-Math.cos(a),-Math.sin(a)));},far);await page.waitForTimeout(300);
 await s.down(0,-38);await waitMode(page,'trunk',15000);await s.up();await page.waitForTimeout(300);await doubleTapStick(page);await page.waitForFunction(()=>window.__village.mode==='ground',null,{timeout:10000});
 const stood=await v(page,()=>{const f=window.__village.player.feet();return Math.hypot(f.x,f.z);});assert.ok(stood>44,`she stands on her feet in the wood, ${stood.toFixed(1)} m out`);
 await page.evaluate(({x,z})=>{const k=window.__village;const a=Math.atan2(z,x);k.sinkAt(x-Math.cos(a)*1.5,z-Math.sin(a)*1.5);},far);await waitMode(page,'grass',5000);await doubleTapStick(page);await page.waitForFunction(()=>window.__village.mode==='ground',null,{timeout:10000});
 // Into a copse trunk, up to the crown, a leap to a neighbour, down, and at the foot into the grass.
 await v(page,()=>{const k=window.__village,t=k.trees[1],a=Math.random()*6.28;const x=t.x+Math.cos(a)*(0.32*t.size+0.6),z=t.z+Math.sin(a)*(0.32*t.size+0.6);k.standAt(x,z,Math.atan2(-(t.x-x),-(t.z-z)));});await page.waitForTimeout(300);
 await s.down(0,-38);await waitMode(page,'trunk',20000);await page.waitForTimeout(500);await page.screenshot({path:out+'/02d-trunk.png'});await waitMode(page,'crown',40000);await s.up();await page.waitForFunction(()=>window.__village.crown&&window.__village.crown.armed,null,{timeout:8000}).catch(()=>{});
 const target=await v(page,()=>{const k=window.__village,t=k.trees[k.crown.tree],o=k.trees.find(o=>o!==t&&Math.hypot(o.x-t.x,o.z-t.z)<=9&&Math.abs(3.4*o.size-3.4*t.size)<=7);k.player.yaw=Math.atan2(-(o.x-t.x),-(o.z-t.z));return o.id;});await page.waitForTimeout(200);
 await s.down(0,-38);await waitMode(page,'hop',10000);await s.up();await waitMode(page,'crown',15000);assert.equal(await v(page,()=>window.__village.crown.tree),target,'leapt across the copse');
 await s.down(0,38);await waitMode(page,'trunk',10000);await waitMode(page,'sink',60000);await s.up();await waitMode(page,'grass',10000);await doubleTapStick(page);await page.waitForFunction(()=>window.__village.mode==='ground',null,{timeout:10000});
 // The noon meal: they arrive at the fire and eat from the stores (the fullest by share), the hunger bars drop, and the bubbles say so.
 const meal=await v(page,()=>{const k=window.__village;k.advance(332-k.tick);const food=()=>k.stores.berries+k.stores.milk+k.stores.grain;const f0=food(),h0=Math.max(...k.hungers());let eating=0;for(let i=0;i<12;i++){k.advance(3);if(k.thoughts().some(t=>t.startsWith('eating')))eating++;}return {f0,f1:food(),h0,h1:Math.max(...k.hungers()),eating,ate:k.village.hobbits.filter(h=>h.ate===Math.floor(k.tick/1440)*3+1).length};});
 assert.ok(meal.eating>=1,`eating shows in a bubble (${JSON.stringify(meal)})`);assert.ok(meal.f1<meal.f0,'the stores are eaten down at noon');assert.ok(meal.ate>=6,`${meal.ate} have eaten by a quarter to one`);
 // Noon: together at the fire, talking; a thought bubble or two.
 await v(page,()=>{window.__village.advance(400-window.__village.tick);window.__village.player.teleport(0,-5,Math.PI);});await page.waitForTimeout(2500);
 const noon=await v(page,()=>({green:window.__village.count('green'),talking:window.__village.village.hobbits.filter(h=>h.activity==='talking').length,labels:window.__village.shown.filter(s=>s.label).length}));assert.ok(noon.green>=7,`${noon.green} at the fire at one o'clock`);assert.ok(noon.talking>=6);assert.ok(noon.labels>=5,`${noon.labels} names round the fire`);
 await page.screenshot({path:out+'/03-noon.png'});
 let bubbles=0;for(let i=0;i<12&&!bubbles;i++){await v(page,()=>window.__village.advance(20));await page.waitForTimeout(250);bubbles=await v(page,()=>window.__village.shown.filter(s=>s.bubble).length);}assert.ok(bubbles>=1,'someone says something at the fire');await page.screenshot({path:out+'/04-talk.png'});
 // Dusk and night: home, the fire lit, windows glowing.
 await v(page,()=>{window.__village.advance(900-window.__village.tick);});await page.waitForTimeout(2000);assert.equal(await v(page,()=>window.__village.count('inside')),8,'all home by night');assert.equal(await v(page,()=>window.__village.figures.filter(f=>f.group.visible).length),0,'nobody shown indoors');
 const night=await v(page,()=>({fireWood:window.__village.fireWood,wood:window.__village.stores.wood}));assert.ok(night.fireWood>0,`Odo laid the night's wood (${JSON.stringify(night)})`);
 await page.screenshot({path:out+'/05-night.png'});
 // A second dawn: out again.
 await v(page,()=>{window.__village.advance(window.__village.dayTicks+200-window.__village.tick);});await page.waitForTimeout(1500);assert.equal(await v(page,()=>window.__village.clock.day),2);assert.equal(await v(page,()=>window.__village.count('inside')),0,'day two, all out again');
 // D1: the village lives and dies. Fed through every meal for days, a child is born into a house with room (told, and the house says so); starved, someone weakens, keeps to the stone, and dies, mourned by the rest; the names change.
 const grown=await v(page,()=>{const k=window.__village,feed=()=>{for(const [s,n] of [['berries',8],['milk',8],['grain',12],['water',10],['wood',12]])k.setStore(s,n);};const n0=k.population;for(let i=0;i<k.dayTicks*4/100&&k.population===n0;i++){feed();k.advance(100);}return {before:n0,after:k.population,events:k.events.map(e=>e.text)};});
 assert.ok(grown.after>grown.before,`fed, a child is born (${JSON.stringify(grown)})`);assert.ok(grown.events.some(e=>e.includes('is born in house')),'the birth is told');
 await page.waitForFunction(()=>{const t=document.getElementById('tip');return !t.hidden&&/is born|goes out|is grown/.test(t.textContent);},null,{timeout:8000}).catch(()=>{});assert.ok(await page.locator('#tip').isVisible(),'the birth is told on screen (the frame after a long advance is slow on the runner)');await page.screenshot({path:out+'/05b-born.png'});
 const lost=await v(page,()=>{const k=window.__village,starve=()=>{for(const s of ['berries','milk','grain'])k.setStore(s,0);for(const l of ['berries','branches','milk'])k.setLand(l,0);};const n0=k.population;for(let i=0;i<k.dayTicks*3/50&&k.population===n0;i++){starve();k.advance(50);}return {before:n0,after:k.population,dead:k.dead.length,events:k.events.map(e=>e.text),mourning:k.thoughts().filter(t=>t.startsWith('mourning')).length,figures:k.figures.length};});
 assert.ok(lost.after<lost.before&&lost.dead>=1,`starved, someone dies (${JSON.stringify(lost)})`);assert.equal(lost.figures,lost.after,'the dead have no figure');assert.ok(lost.events.some(e=>e.endsWith('has died of hunger')),'the death is told');
 await page.waitForTimeout(400);await page.screenshot({path:out+'/05c-mourning.png'});assert.equal(await page.locator('#labels .name:not(.foe):not(.lair):not(.way)').count(),lost.after,'a name for each of the living');
 await v(page,()=>{const k=window.__village;k.reset();});await page.waitForTimeout(300);
 // Reload keeps the village's day; nothing passed while the page was away.
 const before=await v(page,()=>window.__village.tick);await page.reload();await page.click('#begin');await page.waitForFunction(()=>window.__village);await page.waitForTimeout(500);const after=await v(page,()=>window.__village.tick);assert.ok(after>=before&&after-before<10,`kept its day (${before} → ${after})`);
 for(const[name,size]of[['small',{width:375,height:667}],['landscape',{width:844,height:390}],['desktop',{width:1280,height:900}]]){await page.setViewportSize(size);await page.waitForTimeout(600);await page.screenshot({path:out+'/'+name+'.png'});}
 assert.deepEqual(errors,[]);report.push({passed:true,compass:'a strip at the top: cardinal points, the known places with distance; the land goes glassy with the meadow under the grass',forest:'the dark forest drains her by depth; the mother of goats wakes at its heart, hp over her, and takes the strike',level:'kills count; a level owes a choice of vigor, strike or sap',karst:'the free-flow karst stands 330 m north as a feature of the land: its floor her ground, its plants and roots hers as before',chunks:'chunks of hills and trees beyond the meadow, loaded round her; trunk and crown on their trees',pinch:'two fingers, shoulder to overhead, continuous; one more opens the explored map with the village and the karst marked',darkYoung:'one the first night from the wood, to the fullest store, eats its fill, leaves before dawn; up to three',fighting:'strike, thorn burst, root bind on cooldowns and sap; vigor bitten, faint at none, wake weakened',herHands:'a ring at each place fills her stack in seconds, a ring at each store takes it; no forms while loaded',worship:'supplied gatherers pray at the stone; prayer pools; three meals a day',spirits:'a miracle before the stone summons a tireless gatherer, costlier each time',clock:'tap the clock: hours, dawn/noon/dusk/night, x1/x8/x30; ?tick=',outAlways:'trunk, root, grass: out to her feet anywhere, the wood included',land:'berries regrow, branches drop, milk at dawn, strips ripen; all shown by count',stores:'baskets, trough, woodpile, bin, pails on the green, under their caps',gathering:'an armful in the hand, handed over',meals:'noon at the fire and supper home, hunger bars',fire:'Odo lays the wood; the fire is as big as it',stickDoubleTap:'in on the ground, out of any form; no screen taps',oneCamera:'the walking camera rule in every form',herWays:'grass (free, fast), tree roots (faster, held), trunk, crown, leap',thoughts:'always: doing, going, chatter',facing:'forward',hobbits:8,houses:6,rhythm:'dawn out, noon at the fire, night home, day two',clips:'Hulda and the eight hobbits on one skeleton',labels:true,bubbles:true,pausesWhenHidden:'ticks only while watched',saveReload:true,viewports:4});await writeFile(out+'/results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}catch(e){for(const c of browser.contexts())for(const p of c.pages()){await p.screenshot({path:out+'/failure.png'}).catch(()=>{});console.log(await p.evaluate(()=>{const c=window.__village;return c?{tick:c.tick,phase:c.phase,inside:c.count('inside'),green:c.count('green'),status:c.character.status}:null;}).catch(()=>null));}throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
